name:               "Xiangzhu Meng"
description:        "Email:xiangzhu.meng@cripac.ia.ac.cn"

url:                ""
author:             "Xiangzhu Meng"
email:              "xiangzhumeng16@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "xiangzhu_meng"
github:             "xiangzhumeng16"
weixin:             "https://s2.ax1x.com/2019/05/04/EdKXBd.jpg"
facebook:           "xiangzhu_meng"

disqus_shortname:   "xiangzhumeng"

background:         ""

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "https://codeload.github.com/xiangzhumeng16/xiangzhumeng16.github.io/zip/master"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
